global:
  scrape_interval: 5s # Set the scrape interval to every 5 seconds.
  evaluation_interval: 5s # Evaluate rules every 5 seconds.

scrape_configs:
  - job_name: 'observability'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'observability:8080' ]